# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hatchback' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hatchback
  pod ‘Parse’
  pod ‘ParseUI’
  pod 'Paralayout'

end
